# Site settings
title: "Deana Solis"
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  island woman rise
baseurl: "/old_index.html" # the subpath of your site, e.g. /blog/
url: "https://deeesolis.github.io/portfolio/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  deeesolis

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

#title: "Deana Solis"
#logo: /assets/img/logo.png
#description: badges, titles and other artifacts
#show_downloads: false
#theme: jekyll-theme-minimal

#navigation:                # accepts {file, title, url, icon, sidebaricon}
#  - {file: "old_index.html"}
